language: go

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
  - make prep

script: make all test lint

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - go: 1.13.x
