// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package aggstatcmp

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp(in *jlexer.Lexer, out *URLAggDiffStat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Stat":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Stat = make(map[string]*AggDiffStat)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 *AggDiffStat
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(AggDiffStat)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					(out.Stat)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "SumStat":
			(out.SumStat).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp(out *jwriter.Writer, in URLAggDiffStat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Stat\":"
		out.RawString(prefix[1:])
		if in.Stat == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Stat {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if v2Value == nil {
					out.RawString("null")
				} else {
					(*v2Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"SumStat\":"
		out.RawString(prefix)
		(in.SumStat).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URLAggDiffStat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URLAggDiffStat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URLAggDiffStat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URLAggDiffStat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp(l, v)
}
func easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(in *jlexer.Lexer, out *LabelURLAggDiffStat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Started":
			out.Started = int64(in.Int64())
		case "Ended":
			out.Ended = int64(in.Int64())
		case "CmpName":
			out.CmpName = string(in.String())
		case "CmpStarted":
			out.CmpStarted = int64(in.Int64())
		case "CmpEnded":
			out.CmpEnded = int64(in.Int64())
		case "Stat":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Stat = make(map[string]*URLAggDiffStat)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 *URLAggDiffStat
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(URLAggDiffStat)
						}
						(*v3).UnmarshalEasyJSON(in)
					}
					(out.Stat)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(out *jwriter.Writer, in LabelURLAggDiffStat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Started\":"
		out.RawString(prefix)
		out.Int64(int64(in.Started))
	}
	{
		const prefix string = ",\"Ended\":"
		out.RawString(prefix)
		out.Int64(int64(in.Ended))
	}
	{
		const prefix string = ",\"CmpName\":"
		out.RawString(prefix)
		out.String(string(in.CmpName))
	}
	{
		const prefix string = ",\"CmpStarted\":"
		out.RawString(prefix)
		out.Int64(int64(in.CmpStarted))
	}
	{
		const prefix string = ",\"CmpEnded\":"
		out.RawString(prefix)
		out.Int64(int64(in.CmpEnded))
	}
	{
		const prefix string = ",\"Stat\":"
		out.RawString(prefix)
		if in.Stat == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Stat {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil {
					out.RawString("null")
				} else {
					(*v4Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LabelURLAggDiffStat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LabelURLAggDiffStat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LabelURLAggDiffStat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LabelURLAggDiffStat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp1(l, v)
}
func easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(in *jlexer.Lexer, out *AggDiffStat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Elapsed":
			(out.Elapsed).UnmarshalEasyJSON(in)
		case "Connect":
			(out.Connect).UnmarshalEasyJSON(in)
		case "Bytes":
			(out.Bytes).UnmarshalEasyJSON(in)
		case "SentBytes":
			(out.SentBytes).UnmarshalEasyJSON(in)
		case "Errors":
			out.Errors = float64(in.Float64())
		case "SuccessCodes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SuccessCodes = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 float64
					v5 = float64(in.Float64())
					(out.SuccessCodes)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ErrorCodes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ErrorCodes = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 float64
					v6 = float64(in.Float64())
					(out.ErrorCodes)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(out *jwriter.Writer, in AggDiffStat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Elapsed\":"
		out.RawString(prefix[1:])
		(in.Elapsed).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Connect\":"
		out.RawString(prefix)
		(in.Connect).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Bytes\":"
		out.RawString(prefix)
		(in.Bytes).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"SentBytes\":"
		out.RawString(prefix)
		(in.SentBytes).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Errors\":"
		out.RawString(prefix)
		out.Float64(float64(in.Errors))
	}
	{
		const prefix string = ",\"SuccessCodes\":"
		out.RawString(prefix)
		if in.SuccessCodes == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.SuccessCodes {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				out.Float64(float64(v7Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"ErrorCodes\":"
		out.RawString(prefix)
		if in.ErrorCodes == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.ErrorCodes {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				out.Float64(float64(v8Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AggDiffStat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AggDiffStat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB1ab998fEncodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AggDiffStat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AggDiffStat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB1ab998fDecodeGithubComMsaf1980JmeterstatPkgAggstatcmp2(l, v)
}
